version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: |
      cd /tmp/project | ls -lrt

workflows:
  build_and_test:
    jobs:
      - build
